GET https://cosmo-alpaca.westeurope.cloudapp.azure.com/f03a1ec20fd3rest/api/PatrickSchiefer/DOK/v1.0/importData
Authorization: Basic asdf==

####

POST https://cosmo-alpaca.westeurope.cloudapp.azure.com/f03a1ec20fd3rest/api/PatrickSchiefer/DOK/v1.0/importData
Authorization: Basic asdf==
Content-Type: application/json

{
  "data": "test"
}